### ISSUE TITLE
Opening link in new tab

### ISSUE THREAD

**Issue by raffaeldp** [FranckG28/Ratiscrum#15]
The link when you click open in same tab so we loose a user that inss sin in not here. 

So do like when we click on a link like for like go to ratisexe website, it open the site in a new tab please.

Ty

**Comment by jvondermarck** [comment]
i dare to agree with you

**Comment by FranckG28** [comment]
i have headache when i read this issue ...

**Comment by jvondermarck** [comment]
u puss*

**Comment by Kayn017** [comment]
Sorry but I'm afraid the underpants are under the table....

**Comment by raffaeldp** [comment]
> i have headache when i read this issue ...

Create an issue to fix this issue

**Comment by jvondermarck** [comment]
You need to rollmops the issue in Git bash program VBA

**Comment by raffaeldp** [comment]
How can i edit the code please ?

**Comment by jvondermarck** [comment]
> How can i edit the code please ?

you have to create the fork under the line of forkage

**Comment by raffaeldp** [comment]
I am in grève with my french collegue so I do a blocus of this issue

**Comment by raffaeldp** [comment]
🚧🚮🚧🚧🚧🔥🚧🚧🚧🚧🚧🔥🚧🚧🚧🚧🔥🔥🚧🚧🚧🔥🚧🚧🚧🚧🚧🔥

**Comment by jvondermarck** [comment]
If i follow the rule 49 alinea 3 of the GithUB CODE OF CONDUCT, I take the responsibility to close this issue !
